### ISSUE TITLE
maxlength textarea

### ISSUE THREAD

**Issue by byinff** [kevinfaguiar/vue-twemoji-picker#33]
Hi, i have another question. Can i limit the size of textarea input ?

**Comment by byinff** [comment]
I close this issue because i will use the picker emoji only

**Comment by kevinfaguiar** [comment]
I think it is a feature worth developing for those who will use the textarea, even if the focus of the project is the picker. I will flag this as a new feature.

**Comment by kevinfaguiar** [comment]
Enforcing a maxlength prop means I have to check for every possible input event... However the maxlength could be soft, like the Twitter box, where the user can type as it wishes however it will warn the user that he surpassed the limit. Blocking the sending event can be done by the parent component of VueTwemojiPicker.

That said, the spec of this issue is:

- maxlength prop which will give a feedback for the user that he has gone above the maximum limit of characters (think of that like the Twitter textarea) but will not block the input... this should be done on the parent element.

- expose a actualLength value in the "content" prop prototype in the component which calculates the actual length of the textarea (some emojis are considered to be more than one character when using .length in Javascript but are visually and by spec ONE charaacter)

- docs this

**Comment by kevinfaguiar** [comment]
Solved from version 5.2.4 onwards
