### ISSUE TITLE
Non printable caracters are part of 'content' when selecting some Emojis

### ISSUE THREAD

**Issue by COil** [kevinfaguiar/vue-twemoji-picker#54]
Hello, I noticed that selecting some emojis cause to add additional non-printable if the content var (of onEnterKey event for example)

Ex : selection in picker : 🏔️⛰️🌋🗻

First, the count at the right is 6 instead of 4.

Well, that's weird, I can't reproduce now, except for the count that is false. It shows there are 2 extra non-visible characters.

When I debugged at first this issue server-side, I found that this character was inserted between some of the selected Emojis. https://unicode-table.com/fr/FE0F/ with the 65039 code.

See you. COil

**Comment by kevinfaguiar** [comment]
Hi there @COil!

I've just made an update to the direction I wish to go with the TwemojiTextarea and it is available here: https://github.com/kevinfaguiar/vue-twemoji-picker/issues/56#issuecomment-615967495

That said, and considering that emoji unicodes will be counted as two characters, does your issue is still valid?

Thank you taking your time for writing this issue.

**Comment by COil** [comment]
Hello, not a problem for me.
